
package DB;

import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.io.File;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Employee extends javax.swing.JFrame {
    
    PreparedStatement ps;
    ResultSet rs;
    String sql;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YY");
    
    int author_id=0;
    
    public Employee(int id) {
        initComponents();
        this.author_id =id;
    }
    
    public void session(){
        if(author_id==0){
            JOptionPane.showMessageDialog(this,"Please login !");
            Login.main(null);
            dispose();
        }
    }
    
    
    Connection connection(){
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/java_3_5","root","");
            System.out.println("Completed.....");
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println("Connection Error: "+e.getMessage());
            //JOptionPane.showMessageDialog(this, e);
        }
        return con;
    }
    
    public void getData(){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        sql = "SELECT t_user.username,t_employee.* FROM `user` as t_user INNER JOIN `employee` as t_employee ON t_user.id=t_employee.author_id";
        try {
            ps=connection().prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                Object object[]={
                    rs.getString(1),//usernmae
                    rs.getInt(2),//id
                    rs.getString(4),//name
                    rs.getString(5),//gender
                    rs.getString(6),//position
                    rs.getFloat(7),// salary
                    rs.getString(8),//create
                    rs.getString(9),  //address
                    rs.getString(10)
                };
            model.addRow(object);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void clearField(){
        name.setText("");
        bgGender.clearSelection();
        salary.setText("");
        create_at.setDate(null);
        address.setText("");
        images.setIcon(null);
        position.setSelectedIndex(-1);
    }
    
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        images = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        create_at = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txt_image = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setMinimumSize(new java.awt.Dimension(1550, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 150, 45));
        jPanel1.setMinimumSize(new java.awt.Dimension(1550, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/macbook/NetBeansProjects/Java3-5/src/Images/employee.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 400, 410));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Position");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 120, 50));

        name.setColumns(10);
        name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setToolTipText("");
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(255, 0, 0)));
        name.setBounds(new java.awt.Rectangle(10, 10, 0, 0));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 350, 50));
        name.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 50));

        bgGender.add(female);
        female.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, 50));

        bgGender.add(male);
        male.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        male.setSelected(true);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, 50));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 120, 50));

        position.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobile Dev", "Web Dev", "DevOP" }));
        position.setSelectedIndex(-1);
        position.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(255, 0, 0)));
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });
        jPanel1.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 350, 50));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 120, 50));

        salary.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salary.setToolTipText("");
        salary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(255, 0, 0)));
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 350, 50));

        images.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        images.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                imagesPropertyChange(evt);
            }
        });
        jPanel1.add(images, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 180, 190));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 50));

        create_at.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(255, 0, 0)));
        create_at.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(create_at, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 350, 50));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 120, 50));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 360, 150));

        table.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin", "ID", "Name", "Gender", "Position", "Salary", "Date", "Address", "Images"
            }
        ));
        table.setAlignmentX(2.0F);
        table.setAlignmentY(2.0F);
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 940, 240));

        txt_image.setBackground(new java.awt.Color(247, 150, 45));
        txt_image.setFont(new java.awt.Font("Helvetica Neue", 0, 3)); // NOI18N
        txt_image.setForeground(new java.awt.Color(247, 150, 45));
        txt_image.setBorder(null);
        jPanel1.add(txt_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 120, -1, -1));

        id.setBackground(new java.awt.Color(247, 150, 45));
        id.setFont(new java.awt.Font("Helvetica Neue", 0, 3)); // NOI18N
        id.setForeground(new java.awt.Color(247, 150, 45));
        id.setBorder(null);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 80, -1, -1));

        kButton1.setText("Update");
        kButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, -1, -1));

        kButton2.setText("Save");
        kButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        kButton2.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(51, 51, 255));
        kButton2.setkStartColor(new java.awt.Color(0, 51, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 680, -1, -1));

        kButton3.setText("Choose Image");
        kButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        kButton3.setkStartColor(new java.awt.Color(102, 102, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 680, -1, -1));

        kButton4.setText("Delete");
        kButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        kButton4.setkEndColor(new java.awt.Color(255, 102, 102));
        kButton4.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton4.setkStartColor(new java.awt.Color(255, 0, 51));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 680, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 800));

        setSize(new java.awt.Dimension(1550, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        txt_image.setText(filename);
        Image getAbsolutePath=null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(images.getWidth(), images.getHeight(), Image.SCALE_SMOOTH);
        images.setIcon(icon);
        int desiredWidth = 200;
        int desiredHeight = 200;       
        ImageIcon imageIcon = new ImageIcon(filename);
        Image originalImage = imageIcon.getImage();
        Image scaledImage = originalImage.getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        images.setIcon(scaledIcon);
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        String name     = this.name.getText();
        String gender   = (this.male.isSelected()==true)? "Male" : "Female";
        String position = this.position.getSelectedItem().toString();
        float  salary   = Float.parseFloat(this.salary.getText());
        String date     = sdf.format(this.create_at.getDate());
        String address  = this.address.getText();
        String images   = this.txt_image.getText(); 
        try {
            sql = "INSERT INTO `employee`(`author_id`,`name`, `gender`, `position`, `salary`, `create_at`, `address`, `image`) VALUES (?,?,?,?,?,?,?,?)";
            ps=connection().prepareStatement(sql);
            ps.setInt(1, author_id);
            ps.setString(2, name);
            ps.setString(3, gender);
            ps.setString(4, position);
            ps.setFloat(5, salary);
            ps.setString(6, date);
            ps.setString(7, address);
            ps.setString(8, images);
            int i = ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this, "Success!");
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.setRowCount(0);
                getData();
                clearField();
            }else{
                JOptionPane.showMessageDialog(this, "Error!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getData();
        session();
    }//GEN-LAST:event_formWindowOpened

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        int id = Integer.parseInt(this.id.getText());
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        sql = "DELETE FROM `employee` WHERE id=?";
        try {
            ps=connection().prepareStatement(sql);
            ps.setInt(1, id);
            int i=ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this, "Success!");
                model.setRowCount(0);
                getData();
                clearField();
            }else{
                JOptionPane.showMessageDialog(this, "Error!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int row=table.getSelectedRow();
        id.setText(model.getValueAt(row, 1).toString());
        name.setText(model.getValueAt(row, 2).toString());
        String gender=model.getValueAt(row, 3).toString();
        if(gender.equals("Male")){
            male.setSelected(true);
        }else{
            female.setSelected(true);
        }
        position.setSelectedItem(model.getValueAt(row, 4));
        salary.setText(model.getValueAt(row, 5).toString());
        try {
            java.util.Date obj = sdf.parse(model.getValueAt(row, 6).toString());
            create_at.setDate(obj);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        address.setText(model.getValueAt(row, 7).toString());
        txt_image.setText(model.getValueAt(row, 8).toString());
        images.setIcon(new javax.swing.ImageIcon(model.getValueAt(row, 8).toString()));
    }//GEN-LAST:event_tableMouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        String name     = this.name.getText();
        String gender   = (this.male.isSelected()==true)? "Male" : "Female";
        String position = this.position.getSelectedItem().toString();
        float  salary   = Float.parseFloat(this.salary.getText());
        String date     = sdf.format(this.create_at.getDate());
        String address  = this.address.getText();
        String images   = this.txt_image.getText(); 
        int id = Integer.parseInt(this.id.getText());
        sql="UPDATE `employee` SET `author_id`=?, `name`=?,`gender`=?,`position`=?,`salary`=?,`create_at`=?,`address`=?,`image`=? WHERE id=?";
        try {
            ps=connection().prepareStatement(sql);
            ps.setInt(1, author_id);
            ps.setString(2, name);
            ps.setString(3, gender);
            ps.setString(4, position);
            ps.setFloat(5, salary);
            ps.setString(6, date);
            ps.setString(7, address);
            ps.setString(8, images);
            ps.setInt(9, id);
            int i = ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this, "Success!");
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.setRowCount(0);
                getData();
                clearField();
            }else{
                JOptionPane.showMessageDialog(this, "Error!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void imagesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_imagesPropertyChange
        
    }//GEN-LAST:event_imagesPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup bgGender;
    private com.toedter.calendar.JDateChooser create_at;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JLabel images;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField salary;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_image;
    // End of variables declaration//GEN-END:variables

    
}
